### PR TITLE
Update !Help file for 0.2050r

### PR DESCRIPTION
**Pull request by archifishaldev**

### CODE REVIEW

**Review by dpt — APPROVED** [review]

**Comment by dpt** [comment]
Tests are getting wedged. Let's seek @gerph 's help later!

**Comment by gerph** [comment]
> Tests are getting wedged. Let's seek @gerph 's help later!

I've just seen notices from AWS that it the build server has had high load although I didn't see a "I'm rebooting" notice.

I'll have a look this evening when I get in. I did try rerunning in case it was just a transient thing.

**Comment by gerph** [comment]
Hmmm it's timed out this time. I wonder if the build server just needs a bit more time to do it's building.

**Comment by gerph** [comment]
Hmm looks like we are using the json interface. Could probably do with updating to use the robuild client that uses web sockets - won't time out at 10 mins and hopefully might be more interactive whilst it runs. Will have a look when I get home.

**Comment by gerph** [comment]
I'm wondering if the pull request plus push build are the reason that it's failing - running both builds at once was overloading things?

**Pull request merged**
